// lib/ai-service.ts
export type TaskType = 'nutrition' | 'activity' | 'risks' | 'motivation' | 'full' | 'Analyze'

export interface AIPrediction {
  id: number
  task: string
  response: any
  created_at: string
}

export interface RiskItem {
  risk: string
  mitigation: string
  explanation: string
}

export interface NutritionTip {
  tip: string
  caution?: string
  explanation: string
}

export interface ActivityTip {
  tip: string;
  explanation: string;
  frequency: string;
  intensity?: string;
  duration?: string;
  calories_burn?: string;
  benefits?: string[];
  equipment?: string[];
}

export interface MotivationItem {
  message: string
}

export interface FullAnalysis {
  predictions: {
    short_term: string
  }
  recommendations: string[]
  motivational_tip: string
}

export interface NutritionAnalysis {
  analysis: string
  key_problems: string[]
  medical_note: string
  recommendations: Array<{
    tip: string
    explanation: string
    example_foods?: string[]
  }>
  weekly_strategy: string
}

class AIService {
  private baseUrl = 'http://127.0.0.1:8000/api'
  private autoGeneratedKey = 'ai_auto_generated_tasks'
  private autoGenerationTimeKey = 'ai_auto_generation_time'

  async getTodayPredictions(): Promise<AIPrediction[]> {
    const today = new Date().toISOString().split('T')[0]
    const tasks: TaskType[] = ['nutrition', 'activity', 'risks', 'motivation', 'full', 'Analyze']
    
    const predictions = []
    
    for (const task of tasks) {
      try {
        // Handle case sensitivity - API expects 'Analyze' with capital A
        const apiTask = task === 'Analyze' ? 'Analyze' : task
        const response = await fetch(
          `${this.baseUrl}/ai/last-predictions/?task=${apiTask}&date=${today}`,
          {
            credentials: 'include'
          }
        )
        
        if (response.ok) {
          const data = await response.json()
          if (!data.error && Array.isArray(data)) {
            predictions.push(...data)
          }
        }
      } catch (error) {
        console.error(`Error fetching ${task} predictions:`, error)
      }
    }
    
    return predictions.sort((a, b) => 
      new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
    )
  }

  async getPredictionsFromDate(startDate: string, task: TaskType): Promise<AIPrediction[]> {
    try {
      // Handle case sensitivity
      const apiTask = task === 'Analyze' ? 'Analyze' : task
      const response = await fetch(
        `${this.baseUrl}/ai/predictions-from-date/?task=${apiTask}&start_date=${startDate}`,
        {
          credentials: 'include'
        }
      )
      
      if (!response.ok) {
        throw new Error('Failed to fetch predictions')
      }
      
      const data = await response.json()
      if (data.error) {
        throw new Error(data.error)
      }
      
      return Array.isArray(data) ? data : []
    } catch (error) {
      console.error('Error fetching predictions:', error)
      throw error
    }
  }
  // In your ai-service.ts, add this function:

  async generateTaskAnalysis(task: TaskType): Promise<AIPrediction> {
    try {
      // Handle case sensitivity for API endpoint
      const apiTask = task === 'Analyze' ? 'Analyze' : task
      const response = await fetch(
        `${this.baseUrl}/ai/run/${apiTask}/`,
        {
          credentials: 'include'
        }
      )
      
      if (!response.ok) {
        throw new Error('Failed to generate analysis')
      }
      
      const data = await response.json()
      
      return {
        id: Date.now(),
        task: apiTask, // Store with correct case
        response: data,
        created_at: new Date().toISOString()
      }
    } catch (error) {
      console.error(`Error generating ${task} analysis:`, error)
      throw error
    }
  }

  async generateCompleteAnalysis(dateFrom: string, dateTo: string): Promise<AIPrediction> {
    try {
      const response = await fetch(
        `${this.baseUrl}/ai/analyze-nutrition-csv/`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            date_from: dateFrom,
            date_to: dateTo
          }),
          credentials: 'include'
        }
      )
      
      if (!response.ok) {
        throw new Error('Failed to generate complete analysis')
      }
      
      const data = await response.json()
      
      return {
        id: Date.now(),
        task: 'Analyze',
        response: data,
        created_at: new Date().toISOString()
      }
    } catch (error) {
      console.error('Error generating complete analysis:', error)
      throw error
    }
  }

  async autoGenerateDailyTasks() {
    try {
      const today = new Date().toISOString().split('T')[0]
      const lastGenerated = localStorage.getItem(this.autoGeneratedKey)
      const lastGenerationTime = localStorage.getItem(this.autoGenerationTimeKey)
      
      // Check if we already generated today
      if (lastGenerated === today) {
        return false
      }
      
      // Check if it's after 00:30 AM
      const now = new Date()
      const targetTime = new Date()
      targetTime.setHours(0, 30, 0, 0) // 00:30 AM
      
      if (now < targetTime) {
        // Too early, wait until 00:30
        return false
      }
      
      const tasks: TaskType[] = ['nutrition', 'activity', 'risks', 'motivation', 'full']
      
      for (const task of tasks) {
        try {
          // Check if we already have today's prediction
          const todayPredictions = await this.getTodayPredictions()
          const hasTodayPrediction = todayPredictions.some(p => 
            p.task.toLowerCase() === task.toLowerCase() && 
            new Date(p.created_at).toISOString().split('T')[0] === today
          )
          
          if (!hasTodayPrediction) {
            await this.generateTaskAnalysis(task)
            console.log(`Auto-generated ${task} analysis`)
            await new Promise(resolve => setTimeout(resolve, 2000)) // Delay between requests
          }
        } catch (error) {
          console.error(`Failed to auto-generate ${task}:`, error)
        }
      }
      
      // Store generation time
      localStorage.setItem(this.autoGeneratedKey, today)
      localStorage.setItem(this.autoGenerationTimeKey, now.toISOString())
      return true
    } catch (error) {
      console.error('Error in auto-generation:', error)
      return false
    }
  }

  // Check if auto-generation is needed
  async checkAutoGeneration() {
    const now = new Date()
    const today = now.toISOString().split('T')[0]
    const lastGenerated = localStorage.getItem(this.autoGeneratedKey)
    
    // If it's a new day, clear the flag
    if (lastGenerated !== today) {
      localStorage.removeItem(this.autoGeneratedKey)
      localStorage.removeItem(this.autoGenerationTimeKey)
    }
    
    // Check if it's time to generate (after 00:30)
    const targetTime = new Date()
    targetTime.setHours(0, 30, 0, 0) // 00:30 AM
    
    // If it's after 00:30 and we haven't generated today
    if (now >= targetTime && lastGenerated !== today) {
      return await this.autoGenerateDailyTasks()
    }
    
    return false
  }

  // Type guards for response validation
  isRiskResponse(response: any): response is RiskItem[] {
    return Array.isArray(response) && response.every(item => 
      item.risk && item.mitigation && item.explanation
    )
  }


isActivityResponse(response: any): response is ActivityTip[] {
  if (!Array.isArray(response)) return false;
  
  // Check if it looks like activity data - has frequency and tip fields
  return response.every((item: any) => {
    return typeof item === 'object' && 
           item.tip && 
           item.frequency && 
           item.explanation;
  });
}

isNutritionResponse(response: any): response is NutritionTip[] {
  if (!Array.isArray(response)) return false;
  
  // Nutrition data has tip, caution, and explanation
  return response.every((item: any) => {
    return typeof item === 'object' && 
           item.tip && 
           item.explanation;
    // Note: caution might be null, so don't require it
  });
}

  isMotivationResponse(response: any): response is MotivationItem[] {
    return Array.isArray(response) && response.every(item => 
      item.message
    )
  }

  isFullAnalysis(response: any): response is FullAnalysis {
    return response && 
      response.predictions && 
      response.predictions.short_term &&
      Array.isArray(response.recommendations) &&
      response.motivational_tip
  }

  isNutritionAnalysis(response: any): response is NutritionAnalysis {
    return response &&
      response.analysis &&
      Array.isArray(response.key_problems) &&
      response.medical_note &&
      Array.isArray(response.recommendations) &&
      response.weekly_strategy
  }
}
export const exportNutritionCSV = async (userId: number, dateFrom: string, dateTo: string): Promise<Blob> => {
  try {
    const response = await fetch(
      `http://127.0.0.1:8000/api/ai/export-nutrition-csv/?user_id=${userId}&date_from=${dateFrom}&date_to=${dateTo}`,
      {
        method: 'GET',
        headers: {
          'Content-Type': 'text/csv',
        },
      }
    );
    
    if (!response.ok) {
      throw new Error('Failed to export CSV');
    }
    
    return await response.blob();
  } catch (error) {
    console.error('Error exporting CSV:', error);
    throw error;
  }
}
export const aiService = new AIService()